apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mc-chat-app
  template:
    metadata:
      labels:
        app: mc-chat-app
    spec:
      containers:
        - name: mc-chat-app
          image: clarkthedarkshark/mc_chat_app:latest
          ports:
            - containerPort: 3000
