"""Initial migration

Revision ID: 4a8328c9d0ec
Revises: 
Create Date: 2025-01-11 12:04:06.564090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8328c9d0ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_role'), ['role'], unique=False)

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_uploaded_file_session_id')
        batch_op.create_index(batch_op.f('ix_uploaded_file_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_uploaded_file_conversation_id'))
        batch_op.create_index('ix_uploaded_file_session_id', ['session_id'], unique=False)
        batch_op.drop_column('conversation_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_role'))
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))

    # ### end Alembic commands ###
